#!/home/jfernandes/.venv/bin/python
import argparse
import numpy as np
import matplotlib.pyplot as plt

def plot_mf(sfile=None, ufile=None, wall=None, linestyle="line", wu_cut=None, ws_cut=None, figsize=(7, 15), dpi=80, sizef=1, linewidth=2, scatter_size=5, xlim=None, zlim=None):

    """
    Function to plot the manifolds evaliated by the maglib code fpgen.
    
    Parameters
    ----------
    sfile : str
        Path to the file containing the stable manifold data. If none is provided, no stable manifold will be plotted.
    ufile : str
        Path to the file containing the unstable manifold data.
        If none is provided, no unstable manifold will be plotted.
    wall : str
        Path to the file containing the wall data. If none is provided, no wall will be plotted.
    linestyle : str
        Type of line style for the plot: "line", "scatter", or "both". Default is "line".
    wu_cut : int
        Limit the number of points imported from the unstable manifold file. Default is None (impoer the whole file).
    ws_cut : int
        Limit the number of points imported from the stable manifold file. Default is None (impoer the whole file).
    figsize : tuple
        Size of the figure in inches. Default is (7, 15).
    dpi : int
        Dots per inch for the figure. Default is 80 (default is low for better performance).
    sizef : float
        Size factor for the figure (increase or decrease figure size without changig aspect ratio). Default is 1.
    linewidth : int
        Width of the line for the plot. Default is 2.
    scatter_size : int
        Size of the scatter points for the plot, if required. Default is 5.
    xlim : tuple
        Limits for the x-axis. Default is None (no limits).
    zlim : tuple
        Limits for the y-axis. Default is None (no limits).
    
    Returns
    -------
    None
        Displays the plots.

    """

    #load data
    if sfile is not None:
        data_S = np.loadtxt(sfile)
        if ws_cut is not None:
            data_S = data_S[:]
        R_S = data_S[:ws_cut,0]
        Z_S = data_S[:ws_cut,1]

    if ufile is not None:
        data_U = np.loadtxt(ufile)
        if wu_cut is not None:
            data_U = data_U[:ws_cut]
        R_U = data_U[:ws_cut,0]
        Z_U = data_U[:ws_cut,1]

    #load wall
    if wall is not None:
        data_W = np.loadtxt(wall)
        R_wall = data_W[:,0]
        Z_wall = data_W[:,1]

    plt.figure(figsize=(figsize[0]*sizef, figsize[1]*sizef), dpi=dpi)
    plt.gca().set_aspect('equal', adjustable='box')
    if wall:
        plt.plot(R_wall,Z_wall, color="black")
    if sfile is not None:
        if linestyle == "line" or linestyle == "both":
            plt.plot(R_S,Z_S, label="Stable manifold", linewidth=linewidth)
        if linestyle == "scatter" or linestyle == "both":
            plt.scatter(R_S, Z_S, s = scatter_size, label="Stable manifold")
    if ufile is not None:
        if linestyle == "line" or linestyle == "both":
            plt.plot(R_U,Z_U, label="Unstable manifold", linewidth=linewidth)
        if linestyle == "scatter" or linestyle == "both":
            plt.scatter(R_U, Z_U, s = scatter_size, label="Unstable manifold")
    plt.ylabel("Z ( m )", fontsize=12)
    plt.xlabel("R ( m )", fontsize=12)
    if xlim is not None:
        plt.xlim(xlim)
    if zlim is not None:
        plt.ylim(zlim)
    plt.legend()
    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Plot manifolds generated by fpgen.")
    parser.add_argument("--sfile", type=str, default=None, help="Path to the stable manifold file.")
    parser.add_argument("--ufile", type=str, default=None, help="Path to the unstable manifold file.")
    parser.add_argument("--wall", type=str, default=None, help="Path to the wall file.")
    parser.add_argument("--linestyle", type=str, default="line", help="Line style for the plot: 'line', 'scatter', or 'both'.")
    parser.add_argument("--wu_cut", type=int, default=None, help="Limit number of points from unstable manifold file.")
    parser.add_argument("--ws_cut", type=int, default=None, help="Limit number of points from stable manifold file.")
    parser.add_argument("--figsize", type=float, nargs=2, default=(7, 15), help="Figure size in inches.")
    parser.add_argument("--dpi", type=int, default=80, help="Dots per inch for the figure.")
    parser.add_argument("--sizef", type=float, default=1, help="Size factor for the figure.")
    parser.add_argument("--linewidth", type=int, default=2, help="Line width for the plot.")
    parser.add_argument("--scatter_size", type=int, default=5, help="Scatter point size for the plot.")
    parser.add_argument("--xlim", type=float, nargs=2, default=None, help="X-axis limits.")
    parser.add_argument("--zlim", type=float, nargs=2, default=None, help="Z-axis limits.")

    args = parser.parse_args()

    plot_mf(sfile=args.sfile,
            ufile=args.ufile,
            wall=args.wall,
            linestyle=args.linestyle,
            wu_cut=args.wu_cut,
            ws_cut=args.ws_cut,
            figsize=args.figsize,
            dpi=args.dpi,
            sizef=args.sizef,
            linewidth=args.linewidth,
            scatter_size=args.scatter_size,
            xlim=args.xlim,
            zlim=args.zlim
        )