#!/home/jfernandes/.venv/bin/python
"""Push, submit, monitor, pull back, and clean up M3D-C1 scenario-tree cases
on a remote SLURM cluster over SSH.

Operates on a scenario tree generated by generate_scenario.py (see that file
and ../CLAUDE.md for the tree layout and scenario.json schema). Requires a
"cluster" block in scenario.json (host/remote_base_dir/user) that
generate_scenario.py itself does not need or validate. State (linked-status,
SLURM job ID, last-known job state per case) is cached in
<scenario-root>/.remote_state.json between invocations.

Every ssh/rsync round trip is deliberately batched across all selected cases
(one ssh call for push's make_links step, one each for submit/status/clean)
since key-based ssh handshake overhead is non-negligible across the ~48 cases
in a full scenario tree. pull is the one exception: rsync's include/exclude
glob engine can't cheaply be scoped to an arbitrary subset of case
directories in a single call, so pull runs one rsync per eligible case.

Batching is purely a connection-count optimization for whatever subset
--cases selects -- it does not require operating on all cases at once; a
single case is just a batch of size one.
"""
import argparse
import fnmatch
import json
import re
import shlex
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import generate_scenario as gs

STATE_FILE_NAME = ".remote_state.json"

REQUIRED_CLUSTER_KEYS = ["host", "remote_base_dir", "user"]

# Mirrors generate_scenario.RMALL_CONTENT's cleanup targets ("rm -rf C1ke
# normcurv *out profiles* *.h5") plus C1stdout, which the batch script writes
# but rmall doesn't clean up. Kept as a separate literal rather than parsed
# out of RMALL_CONTENT's free-text rm line -- not worth the fragility for one
# small static list.
OUTPUT_ARTIFACT_GLOBS = ["C1stdout", "*.h5", "C1ke", "normcurv", "*out", "profiles*"]

NONTERMINAL_SLURM_STATES = {
    "PENDING", "RUNNING", "CONFIGURING", "COMPLETING", "SUSPENDED", "SUBMITTED",
}
TERMINAL_FAILURE_STATES = {
    "FAILED", "CANCELLED", "TIMEOUT", "OUT_OF_MEMORY", "NODE_FAIL", "BOOT_FAIL", "DEADLINE",
}

SUBMIT_MARKER_RE = re.compile(r"^SUBMIT (\S+)$")
SBATCH_JOBID_RE = re.compile(r"^Submitted batch job (\d+)$")
# Shared shape for push's "LINKRESULT <relpath> <exit_code>" and clean's
# "CLEANRESULT <relpath> <exit_code>" marker lines -- see parse_result_lines.
RESULT_MARKER_RE = re.compile(r"^(\S+) (\S+) (\d+)$")


# ---------------------------------------------------------------------------
# config / state
# ---------------------------------------------------------------------------

def load_cluster_config(root):
    """Load scenario.json's "cluster" block.

    Parameters
    ----------
    root : Path
        Root directory of the scenario tree (contains scenario.json).

    Returns
    -------
    dict
        The "cluster" sub-dict with keys host/remote_base_dir/user.
    """
    config = gs.load_config(root / "scenario.json")
    cluster = config.get("cluster")
    if cluster is None:
        raise SystemExit(
            f"{root / 'scenario.json'} has no 'cluster' block -- required by remote_run.py "
            "(host/remote_base_dir/user), see template/CLAUDE.md"
        )
    missing = [k for k in REQUIRED_CLUSTER_KEYS if k not in cluster]
    if missing:
        raise SystemExit(f"scenario.json 'cluster' block missing key(s): {', '.join(missing)}")
    return cluster


def remote_target(cluster):
    return f"{cluster['host']}:{cluster['remote_base_dir']}"


def load_state(root):
    """Load <root>/.remote_state.json, or an empty state if absent.

    Parameters
    ----------
    root : Path
        Root directory of the scenario tree.

    Returns
    -------
    dict
        {"remote_target": str or None, "cases": {relpath: {...}}}
    """
    path = root / STATE_FILE_NAME
    if not path.exists():
        return {"remote_target": None, "cases": {}}
    return json.loads(path.read_text())


def save_state(root, state):
    """Write state back to <root>/.remote_state.json."""
    (root / STATE_FILE_NAME).write_text(json.dumps(state, indent=2, sort_keys=True) + "\n")


def check_remote_target(state, cluster):
    """Guard against reusing cached job IDs/linked-flags against a different
    remote host/directory than the one they were recorded against. Updates
    state in place with the current target on first use."""
    current = remote_target(cluster)
    recorded = state.get("remote_target")
    if recorded is not None and recorded != current:
        raise SystemExit(
            f"scenario.json's cluster target ({current}) does not match the target recorded in "
            f"{STATE_FILE_NAME} ({recorded}). Cached job IDs/linked-flags may refer to a "
            "different remote location -- resolve manually before continuing "
            "(e.g. delete .remote_state.json if this is intentional)."
        )
    state["remote_target"] = current


def utc_now_iso():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def parse_job_name(case_dir):
    """Read the #SBATCH -J line out of a case's own batch_script.response,
    rather than recomputing it from FLUID_PARAMS, so it can never drift from
    what was actually submitted."""
    batch = (case_dir / "batch_script.response").read_text()
    m = gs.JOB_NAME_LINE_RE.search(batch)
    if not m:
        raise SystemExit(f"{case_dir / 'batch_script.response'}: could not find #SBATCH -J line")
    return m.group(1)


# ---------------------------------------------------------------------------
# case selection
# ---------------------------------------------------------------------------

def select_cases(root, cases_arg):
    """Discover case directories and filter them by the --cases selector.

    Parameters
    ----------
    root : Path
        Root directory of the scenario tree.
    cases_arg : str or None
        Comma-separated fnmatch glob patterns matched against case relpaths
        (e.g. "n1/*/coil_sets_1kAt/CPL_set_000"). None selects every case.

    Returns
    -------
    list of (Path, str)
        (case_dir, relpath) pairs, sorted by relpath.
    """
    cases, malformed = gs.discover_cases(root)
    if malformed:
        print(f"warning: {len(malformed)} malformed case-like director"
              f"{'y' if len(malformed) == 1 else 'ies'} ignored "
              "(run generate_scenario.py validate for details)", file=sys.stderr)
    all_cases = [(path, rel) for path, rel, _m in cases]

    if cases_arg is None:
        selected = all_cases
    else:
        patterns = [p.strip() for p in cases_arg.split(",") if p.strip()]
        selected = [(path, rel) for path, rel in all_cases
                    if any(fnmatch.fnmatch(rel, pat) for pat in patterns)]

    if not selected:
        raise SystemExit(f"--cases {cases_arg!r} matched no case directories under {root}")
    return selected


# ---------------------------------------------------------------------------
# ssh / rsync primitives
# ---------------------------------------------------------------------------

def ssh_run(cluster, script_text):
    """Run a bash script on the remote host over ssh, piped via stdin.

    stderr is not captured -- it streams straight to the user's terminal, so
    remote command failures surface with their original messages intact.

    Parameters
    ----------
    cluster : dict
        Cluster config (needs "host").
    script_text : str
        Bash script body, executed as `ssh <host> bash -s`.

    Returns
    -------
    str
        The remote command's stdout.
    """
    result = subprocess.run(
        ["ssh", cluster["host"], "bash", "-s"],
        input=script_text, text=True, stdout=subprocess.PIPE, check=True,
    )
    return result.stdout


def rsync_push(cluster, root, cases):
    """rsync the known input files for `cases` from local to remote.

    Only files that exist locally and are named in generate_scenario.CASE_FILES
    are transferred; never touches remote-side solver output (not in that
    set). --checksum (not mtime/size) because generate_scenario.py init
    --force rewrites file bytes on every re-render even when content is
    unchanged for a given axis combination.

    Parameters
    ----------
    cluster : dict
    root : Path
    cases : list of (Path, str)
        (case_dir, relpath) pairs to push.
    """
    filelist_lines = [
        f"{rel}/{name}"
        for path, rel in cases
        for name in gs.CASE_FILES
        if (path / name).exists()
    ]
    if not filelist_lines:
        print("push: nothing to transfer (no known input files found locally)")
        return

    dest = f"{cluster['host']}:{cluster['remote_base_dir']}/"
    subprocess.run(
        ["rsync", "-a", "--checksum", "--files-from=-", "--relative", f"{root}/", dest],
        input="\n".join(filelist_lines) + "\n", text=True, check=True,
    )


def rsync_pull_case(cluster, root, relpath):
    """rsync the known output artifacts for one case from remote to local.
    No --delete: pulling must never remove a local file just because it's
    absent remotely."""
    src = f"{cluster['host']}:{cluster['remote_base_dir']}/{relpath}/"
    args = ["rsync", "-a"]
    for pattern in OUTPUT_ARTIFACT_GLOBS:
        args.append(f"--include={pattern}")
    args += ["--exclude=*", src, f"{root / relpath}/"]
    subprocess.run(args, check=True)


def build_link_script(cluster, relpaths_to_link):
    """Bash script for push's ssh round trip: ensure remote_base_dir exists,
    then run ./make_links for each relpath, reporting per-case exit codes so
    Python can attribute results back to individual local state entries.
    Deliberately not wrapped in `set -e` -- one case's failure must not abort
    the rest of the batch."""
    lines = [f"mkdir -p {shlex.quote(cluster['remote_base_dir'])}"]
    for rel in relpaths_to_link:
        remote_dir = f"{cluster['remote_base_dir']}/{rel}"
        lines.append(
            f'(cd {shlex.quote(remote_dir)} && ./make_links); echo "LINKRESULT {rel} $?"'
        )
    return "\n".join(lines) + "\n"


def parse_result_lines(stdout, marker):
    """Parse '<marker> <relpath> <exit_code>' lines into {relpath: code}.
    Shared by push's LINKRESULT and clean's CLEANRESULT markers."""
    results = {}
    for line in stdout.splitlines():
        m = RESULT_MARKER_RE.match(line)
        if m and m.group(1) == marker:
            results[m.group(2)] = int(m.group(3))
    return results


def build_submit_script(cluster, relpaths):
    """Bash script for submit's ssh round trip: sbatch each case, each
    preceded by a 'SUBMIT <relpath>' marker line so Python can pair sbatch's
    own 'Submitted batch job <id>' output back to the right case."""
    lines = []
    for rel in relpaths:
        remote_dir = f"{cluster['remote_base_dir']}/{rel}"
        lines.append(f'echo "SUBMIT {rel}"')
        lines.append(f"(cd {shlex.quote(remote_dir)} && sbatch batch_script.response)")
    return "\n".join(lines) + "\n"


def parse_sbatch_output(stdout):
    """Parse combined 'SUBMIT <relpath>' / 'Submitted batch job <id>' pairs.

    Returns
    -------
    dict
        relpath -> job_id (str), only for cases where a job ID was found.
    """
    job_ids = {}
    current = None
    for line in stdout.splitlines():
        m = SUBMIT_MARKER_RE.match(line)
        if m:
            current = m.group(1)
            continue
        m = SBATCH_JOBID_RE.match(line)
        if m and current is not None:
            job_ids[current] = m.group(1)
            current = None
    return job_ids


def build_status_script(job_ids):
    """sacct is the primary source (squeue drops jobs the instant they leave
    the queue, so it can't distinguish completed/failed/never-existed);
    squeue is queried in the same round trip as a fallback for jobs sacct
    hasn't caught up on yet right after submission."""
    ids_csv = ",".join(job_ids)
    return (
        f"sacct -j {ids_csv} --format=JobID,State --parsable2 --noheader\n"
        "echo '---SQUEUE---'\n"
        f"squeue -j {ids_csv} --format='%i|%T' --noheader\n"
    )


def build_clean_script(cluster, relpaths):
    """Bash script for clean's ssh round trip: run each case's own ./rmall
    (the existing per-case output-cleanup script) rather than reimplementing
    file removal here, so clean can never drift from what a manual single-case
    cleanup already does. Reports per-case exit codes like build_link_script.
    Not wrapped in `set -e` -- one case's failure must not abort the batch."""
    lines = []
    for rel in relpaths:
        remote_dir = f"{cluster['remote_base_dir']}/{rel}"
        lines.append(
            f'(cd {shlex.quote(remote_dir)} && ./rmall); echo "CLEANRESULT {rel} $?"'
        )
    return "\n".join(lines) + "\n"


def parse_status_output(stdout, job_ids):
    """Parse combined sacct + squeue output into {job_id: state}, preferring
    sacct's bare JobID row (skipping .batch/.extern sub-steps) and falling
    back to squeue for any job ID sacct didn't report."""
    sacct_part, _, squeue_part = stdout.partition("---SQUEUE---")
    states = {}
    for line in sacct_part.splitlines():
        line = line.strip()
        if not line or "|" not in line:
            continue
        jid, jstate = line.split("|", 1)
        if "." in jid:
            continue
        states[jid] = jstate.split()[0] if jstate.strip() else "UNKNOWN"

    for line in squeue_part.splitlines():
        line = line.strip()
        if not line or "|" not in line:
            continue
        jid, jstate = line.split("|", 1)
        states.setdefault(jid, jstate)

    return {jid: states.get(jid, "UNKNOWN") for jid in job_ids}


# ---------------------------------------------------------------------------
# subcommands
# ---------------------------------------------------------------------------

def cmd_push(args):
    root = Path(args.path).resolve()
    cluster = load_cluster_config(root)
    state = load_state(root)
    check_remote_target(state, cluster)
    cases = select_cases(root, args.cases)

    to_link = [rel for _path, rel in cases
               if args.force_relink or not state["cases"].get(rel, {}).get("linked", False)]
    link_script = build_link_script(cluster, to_link)

    if args.dry_run:
        filelist = [f"{rel}/{name}" for path, rel in cases
                    for name in gs.CASE_FILES if (path / name).exists()]
        print("--- rsync file list ---")
        print("\n".join(filelist))
        print("--- ssh (make_links) ---")
        print(link_script, end="")
        return

    # rsync first: make_links needs the case directory (and the make_links
    # script itself) to already exist remotely, which on a fresh
    # remote_base_dir is only true after this transfer -- --relative makes
    # rsync create the full directory tree, so no separate mkdir is needed.
    rsync_push(cluster, root, cases)

    stdout = ssh_run(cluster, link_script)
    print(stdout, end="")
    results = parse_result_lines(stdout, "LINKRESULT")
    for rel, code in results.items():
        state["cases"].setdefault(rel, {})
        if code == 0:
            state["cases"][rel]["linked"] = True
        else:
            print(f"warning: make_links failed for {rel} (exit {code}), left unlinked", file=sys.stderr)

    save_state(root, state)
    print(f"push: transferred input files for {len(cases)} case(s)")


def cmd_submit(args):
    root = Path(args.path).resolve()
    cluster = load_cluster_config(root)
    state = load_state(root)
    check_remote_target(state, cluster)
    cases = select_cases(root, args.cases)

    eligible = []
    for path, rel in cases:
        case_state = state["cases"].get(rel, {})
        last_state = case_state.get("last_state")
        if last_state in NONTERMINAL_SLURM_STATES and not args.force:
            print(f"skip {rel}: already has active job {case_state.get('job_id')} "
                  f"(state={last_state}), use --force to resubmit")
            continue
        eligible.append((path, rel))

    if not eligible:
        print("submit: nothing to submit")
        return

    script = build_submit_script(cluster, [rel for _p, rel in eligible])

    if args.dry_run:
        print("--- ssh (sbatch) ---")
        print(script, end="")
        return

    stdout = ssh_run(cluster, script)
    print(stdout, end="")
    job_ids = parse_sbatch_output(stdout)

    now = utc_now_iso()
    for path, rel in eligible:
        job_id = job_ids.get(rel)
        if job_id is None:
            print(f"warning: no job ID parsed for {rel}, sbatch may have failed", file=sys.stderr)
            continue
        state["cases"].setdefault(rel, {})
        state["cases"][rel].update({
            "job_id": job_id,
            "job_name": parse_job_name(path),
            "submitted_at": now,
            "last_state": "SUBMITTED",
        })

    save_state(root, state)
    print(f"submit: {len(job_ids)}/{len(eligible)} case(s) submitted")


def cmd_status(args):
    root = Path(args.path).resolve()
    cluster = load_cluster_config(root)
    state = load_state(root)
    check_remote_target(state, cluster)
    cases = select_cases(root, args.cases)

    with_job = [(rel, state["cases"][rel]["job_id"]) for _p, rel in cases
                if state["cases"].get(rel, {}).get("job_id")]
    n_no_job = len(cases) - len(with_job)

    if with_job:
        job_ids = [jid for _rel, jid in with_job]
        stdout = ssh_run(cluster, build_status_script(job_ids))
        job_states = parse_status_output(stdout, job_ids)
        now = utc_now_iso()
        for rel, jid in with_job:
            state["cases"][rel]["last_state"] = job_states[jid]
            state["cases"][rel]["last_checked_at"] = now

    save_state(root, state)

    n_completed = n_failed = n_flight = 0
    for _path, rel in cases:
        case_state = state["cases"].get(rel, {})
        jid = case_state.get("job_id")
        if jid is None:
            print(f"{rel}: no job submitted")
            continue
        st = case_state.get("last_state", "UNKNOWN")
        print(f"{rel}: job={jid} state={st}")
        if st == "COMPLETED":
            n_completed += 1
        elif st in TERMINAL_FAILURE_STATES:
            n_failed += 1
        else:
            n_flight += 1

    print(f"\n{n_completed} completed, {n_failed} failed, {n_flight} in flight, "
          f"{n_no_job} not submitted")


def cmd_pull(args):
    root = Path(args.path).resolve()
    cluster = load_cluster_config(root)
    state = load_state(root)
    check_remote_target(state, cluster)
    cases = select_cases(root, args.cases)

    eligible = []
    for _path, rel in cases:
        case_state = state["cases"].get(rel, {})
        job_id = case_state.get("job_id")
        if job_id is None:
            print(f"skip {rel}: no job submitted")
            continue
        last_state = case_state.get("last_state")
        if last_state != "COMPLETED" and not args.all:
            print(f"skip {rel}: state={last_state} (use --all to pull anyway)")
            continue
        eligible.append(rel)

    if not eligible:
        print("pull: nothing to pull")
        return

    if args.dry_run:
        for rel in eligible:
            print(f"rsync {remote_target(cluster)}/{rel}/ -> {root / rel}/  "
                  f"(globs: {', '.join(OUTPUT_ARTIFACT_GLOBS)})")
        return

    now = utc_now_iso()
    for rel in eligible:
        rsync_pull_case(cluster, root, rel)
        state["cases"][rel]["pulled_at"] = now
        print(f"pulled {rel}")

    save_state(root, state)


def cmd_clean(args):
    root = Path(args.path).resolve()
    cluster = load_cluster_config(root)
    state = load_state(root)
    check_remote_target(state, cluster)
    cases = select_cases(root, args.cases)

    eligible = []
    for _path, rel in cases:
        case_state = state["cases"].get(rel, {})
        job_id = case_state.get("job_id")
        if job_id is None:
            print(f"skip {rel}: no job submitted, nothing to clean")
            continue
        last_state = case_state.get("last_state")
        if last_state in NONTERMINAL_SLURM_STATES:
            # Never overridable by --force: rmall would delete output files a
            # running/pending job is actively writing.
            print(f"skip {rel}: job is still {last_state}, refusing to clean a live run's output")
            continue
        if last_state != "COMPLETED" or not case_state.get("pulled_at"):
            if not args.force:
                print(f"skip {rel}: state={last_state}, pulled="
                      f"{'yes' if case_state.get('pulled_at') else 'no'} (use --force to clean anyway)")
                continue
        eligible.append(rel)

    if not eligible:
        print("clean: nothing to clean")
        return

    script = build_clean_script(cluster, eligible)

    if args.dry_run:
        print("--- ssh (rmall) ---")
        print(script, end="")
        return

    stdout = ssh_run(cluster, script)
    print(stdout, end="")
    results = parse_result_lines(stdout, "CLEANRESULT")
    now = utc_now_iso()
    for rel, code in results.items():
        if code == 0:
            state["cases"][rel]["cleaned_at"] = now
        else:
            print(f"warning: rmall failed for {rel} (exit {code})", file=sys.stderr)

    save_state(root, state)
    print(f"clean: cleaned {len(results)}/{len(eligible)} case(s)")


# ---------------------------------------------------------------------------

def add_common_args(p):
    p.add_argument("--path", default=".", help="root directory of the scenario tree (default: .)")
    p.add_argument("--cases", default=None,
                    help="comma-separated fnmatch glob(s) against case relpaths "
                         "(e.g. 'n1/*/coil_sets_1kAt/CPL_set_000'); default: all cases")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)

    p_push = sub.add_parser("push", help="push case input files and run make_links on the cluster")
    add_common_args(p_push)
    p_push.add_argument("--force-relink", action="store_true", help="re-run make_links even if already linked")
    p_push.add_argument("--dry-run", action="store_true", help="print planned ssh/rsync commands without running them")
    p_push.set_defaults(func=cmd_push)

    p_submit = sub.add_parser("submit", help="submit case batch_script.response via sbatch")
    add_common_args(p_submit)
    p_submit.add_argument("--force", action="store_true", help="resubmit even if a non-terminal job is already tracked")
    p_submit.add_argument("--dry-run", action="store_true", help="print the planned sbatch script without running it")
    p_submit.set_defaults(func=cmd_submit)

    p_status = sub.add_parser("status", help="check SLURM job status for tracked cases")
    add_common_args(p_status)
    p_status.set_defaults(func=cmd_status)

    p_pull = sub.add_parser("pull", help="pull back solver output artifacts for completed cases")
    add_common_args(p_pull)
    p_pull.add_argument("--all", action="store_true", help="pull regardless of tracked job state (default: only COMPLETED)")
    p_pull.add_argument("--dry-run", action="store_true", help="print planned rsync commands without running them")
    p_pull.set_defaults(func=cmd_pull)

    p_clean = sub.add_parser("clean", help="run ./rmall remotely to remove solver output for already-pulled cases")
    add_common_args(p_clean)
    p_clean.add_argument("--force", action="store_true",
                          help="clean even if not confirmed COMPLETED+pulled "
                               "(never overrides the running-job guard)")
    p_clean.add_argument("--dry-run", action="store_true", help="print the planned rmall script without running it")
    p_clean.set_defaults(func=cmd_clean)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
