#!/home/jfernandes/.venv/bin/python
import argparse
import numpy as np


def flare_chirikov(surfmn_npz: str, filename: str) -> None:
    """
    Compute island widths and the Chirikov overlap parameter from a
    flare_surfmn.py output file, following M3D-C1's IDL
    island_widths.pro/chirikov.pro:

        width = (2/pi) * sqrt( (area * Bmn[T] / |m * psiprime|) * |q / qprime| )
        chi[j] = (width[j] + width[j+1]) / 2 / |psiN_res[j+1] - psiN_res[j]|

    where psiprime = d(poloidal flux)/d(psiN) / (2*pi) (a single constant for
    the whole equilibrium, since psiN is by definition linear in poloidal
    flux) and qprime = dq/dpsiN, both evaluated at the resonant surfaces.

    Pure post-processing: does not touch FLARE/M3D-C1 -- everything needed
    (db_res, area_res, qprime_res, psiprime) is already in the .npz written
    by flare_surfmn.py. This means it is agnostic to how that .npz's field
    was built, including a phase/amplitude-superposed multi-coil-set model
    (flare_model_gen.py/flare_phase_map.py) -- the superposition is already
    baked into db_res by the time it reaches this function.

    Parameters
    ----------
    surfmn_npz : str
        Path to a .npz produced by flare_surfmn.py (must include the
        area_res/qprime_res/psiprime keys).
    filename : str
        Output filename for the Chirikov data.

    Returns
    -------
    None
        Saves the Chirikov data to a .npz file.
    """
    d = np.load(surfmn_npz)
    for key in ("area_res", "qprime_res", "psiprime"):
        if key not in d.files:
            raise ValueError(
                f"{surfmn_npz!r} is missing '{key}' -- it was generated by an "
                "older flare_surfmn.py that predates Chirikov support; regenerate it."
            )

    n_tor = int(d["n_tor"])
    m_res = d["m_res"]
    psiN_res = d["psiN_res"]
    q_res = d["q_res"]
    area_res = d["area_res"]
    qprime_res = d["qprime_res"]
    psiprime = float(d["psiprime"])
    bmn_T = d["db_res"] / 1e4  # G -> T

    order = np.argsort(psiN_res)
    m_res, psiN_res, q_res = m_res[order], psiN_res[order], q_res[order]
    area_res, qprime_res, bmn_T = area_res[order], qprime_res[order], bmn_T[order]

    width_res = (2.0 / np.pi) * np.sqrt(
        (area_res * bmn_T / np.abs(m_res * psiprime)) * np.abs(q_res / qprime_res)
    )  # units: psiN

    chirikov = (width_res[:-1] + width_res[1:]) / 2.0 / np.abs(np.diff(psiN_res))
    psimid = (psiN_res[:-1] + psiN_res[1:]) / 2.0
    m_pairs = np.column_stack((m_res[:-1], m_res[1:]))

    if not filename.endswith(".npz"):
        filename += ".npz"
    np.savez(
        filename,
        n_tor=n_tor,
        m_res=m_res,
        psiN_res=psiN_res,
        q_res=q_res,
        width_res=width_res,
        chirikov=chirikov,
        psimid=psimid,
        m_pairs=m_pairs,
    )
    print(f"Data saved to {filename}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Compute Chirikov overlap parameter from flare_surfmn.py output.")
    parser.add_argument("surfmn_npz", type=str, help="Path to a flare_surfmn.py .npz output file")
    parser.add_argument("filename", type=str, help="Output filename for the Chirikov data")
    args = parser.parse_args()

    flare_chirikov(surfmn_npz=args.surfmn_npz, filename=args.filename)
