#!/home/jfernandes/.venv/bin/python
"""Validate flare_chirikov.py against IDL's island_widths.pro/chirikov.pro,
run directly on a bmn NetCDF reference (the same kind of file consumed by
validate_surfmn.py).

Unlike validate_surfmn.py, the IDL reference here is not itself a pre-shipped
.nc file: it is generated by loading the resonant-surface arrays directly out
of a bmn NetCDF via IDL's own read_bmn.pro (m, psiN, q, qprime, area,
psiprime, |Bmn|) and, separately, via island_widths.pro (width(psiN)). The
IDL-side driver used to produce that reference for shot0009/n3 is documented
alongside this file (run_chirikov_validation.pro); chirikov.pro itself could
not be called directly under this IDL install (its `if(width eq 0)` error
sentinel check raises "Expression must be a scalar..." on a real, multi-point
success array -- a pre-existing incompatibility with modern IDL, unrelated to
this port), so the Chirikov parameter is instead computed in IDL directly
from island_widths.pro's own output, using chirikov.pro's documented formula
verbatim:

    chi[j] = (width[j] + width[j+1]) / 2 / |psiN[j+1] - psiN[j]|

This script aligns FLARE's and IDL's resonant-surface arrays by poloidal mode
number `m` (not index -- the two codes may keep a different subset of
resonant surfaces near the edges of the q-profile range) and reports relative
error for each ingredient (q, qprime, area, psiprime, |Bmn|) as well as the
final island width and Chirikov parameter.
"""
from __future__ import annotations

import argparse

import numpy as np


def load_idl_resonant(path: str) -> dict:
    """Load IDL's `m psin q qprime area psiprime bmn_G phase_rad` columns
    (as written by run_chirikov_validation.pro's read_bmn() dump)."""
    data = np.loadtxt(path)
    keys = ["m", "psiN", "q", "qprime", "area", "psiprime", "bmn", "phase"]
    return {k: data[:, i] for i, k in enumerate(keys)}


def load_idl_width(path: str) -> dict:
    data = np.loadtxt(path)
    return dict(psiN=data[:, 0], q=data[:, 1], width=data[:, 2])


def load_idl_chirikov(path: str) -> dict:
    data = np.loadtxt(path)
    return dict(psimid=data[:, 0], chirikov=data[:, 1])


def align_by_m(m_a: np.ndarray, m_b: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return (common_m, index_into_a, index_into_b) aligning two resonant-surface
    arrays by integer poloidal mode number (not position)."""
    common_m = np.intersect1d(m_a.astype(int), m_b.astype(int))
    a_pos = {v: i for i, v in enumerate(m_a.astype(int))}
    b_pos = {v: i for i, v in enumerate(m_b.astype(int))}
    ia = np.array([a_pos[v] for v in common_m])
    ib = np.array([b_pos[v] for v in common_m])
    return common_m, ia, ib


def rel_err(a: np.ndarray, b: np.ndarray) -> dict:
    """Relative error of `a` against reference `b`."""
    e = np.abs(a - b) / np.abs(b)
    return dict(err=e, rms=float(np.sqrt(np.mean(e ** 2))), median=float(np.median(e)),
                p95=float(np.percentile(e, 95)), max=float(np.max(e)))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("surfmn_npz", help="flare_surfmn.py .npz output (must include area_res/qprime_res/psiprime)")
    ap.add_argument("chirikov_npz", help="flare_chirikov.py .npz output")
    ap.add_argument("idl_resonant_txt", help="IDL read_bmn() dump: m psin q qprime area psiprime bmn_G phase_rad")
    ap.add_argument("idl_width_txt", help="IDL island_widths() dump: psin q width")
    ap.add_argument("idl_chirikov_txt", help="IDL chirikov-formula dump: psimid chirikov")
    args = ap.parse_args()

    surfmn = np.load(args.surfmn_npz)
    chir = np.load(args.chirikov_npz)
    idl_res = load_idl_resonant(args.idl_resonant_txt)
    idl_width = load_idl_width(args.idl_width_txt)
    idl_chi = load_idl_chirikov(args.idl_chirikov_txt)

    print(f"psiprime: FLARE={float(surfmn['psiprime']):.6e}  IDL={idl_res['psiprime'][0]:.6e}  "
          f"rel.err={abs(abs(float(surfmn['psiprime'])) - abs(idl_res['psiprime'][0])) / abs(idl_res['psiprime'][0]):.4f}")

    # --- per-resonant-surface ingredients, aligned by m ---
    common_m, ia, ib = align_by_m(surfmn["m_res"], idl_res["m"])
    print(f"\n{len(common_m)} resonant surfaces in common (FLARE has {len(surfmn['m_res'])}, "
          f"IDL has {len(idl_res['m'])}): m = {common_m}")

    for label, flare_arr, idl_arr in [
        ("psiN", surfmn["psiN_res"], idl_res["psiN"]),
        ("q", surfmn["q_res"], idl_res["q"]),
        ("qprime", surfmn["qprime_res"], idl_res["qprime"]),
        ("area", surfmn["area_res"], idl_res["area"]),
        ("|Bmn| (G)", surfmn["db_res"], idl_res["bmn"]),
    ]:
        stats = rel_err(flare_arr[ia], idl_arr[ib])
        print(f"  {label:12s}: RMS={stats['rms']:.4f} median={stats['median']:.4f} "
              f"p95={stats['p95']:.4f} max={stats['max']:.4f}")

    # --- island width, aligned by m (chirikov_npz's m_res matches surfmn_npz's) ---
    # idl_width.txt (island_widths.pro's own dump) carries no m column, but shares
    # index order with idl_resonant.txt (read_bmn's dump), which does.
    common_m_w, ia_w, ib_w = align_by_m(chir["m_res"], idl_res["m"])
    idl_width_by_m = idl_width["width"][ib_w]
    width_stats = rel_err(chir["width_res"][ia_w], idl_width_by_m)
    print(f"\n  {'width':12s}: RMS={width_stats['rms']:.4f} median={width_stats['median']:.4f} "
          f"p95={width_stats['p95']:.4f} max={width_stats['max']:.4f}")

    # --- Chirikov parameter, aligned by adjacent-m-pair midpoint psiN ---
    psimid_flare = chir["psimid"]
    psimid_idl = idl_chi["psimid"]
    # Align by nearest psimid (both are sorted ascending in psiN by construction)
    order_idl = np.argsort(psimid_idl)
    psimid_idl_sorted = psimid_idl[order_idl]
    chi_idl_sorted = idl_chi["chirikov"][order_idl]
    chi_idl_interp = np.interp(psimid_flare, psimid_idl_sorted, chi_idl_sorted)
    chi_stats = rel_err(chir["chirikov"], chi_idl_interp)
    print(f"  {'chirikov':12s}: RMS={chi_stats['rms']:.4f} median={chi_stats['median']:.4f} "
          f"p95={chi_stats['p95']:.4f} max={chi_stats['max']:.4f}")

    print("\npsimid  chirikov(FLARE)  chirikov(IDL, interp)  rel.err")
    for i in range(len(psimid_flare)):
        print(f"{psimid_flare[i]:.4f}  {chir['chirikov'][i]:14.4f}  {chi_idl_interp[i]:20.4f}  "
              f"{chi_stats['err'][i]:.4f}")


if __name__ == "__main__":
    main()
